'use client';
import {useState,useEffect,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {ArrowRight,Footprints,Check,CircleHelp,TriangleAlert} from 'lucide-react';
import {requirements,actions,exportReview,type CallResult,type Action} from '@/lib/domain';
import {restaurant} from '@/lib/knowledge';
import {sample,scenarios,type Scenario} from '@/lib/fixtures';
const labels={requested:'Customer requested',not_requested:'Customer explicitly does not need this',unknown:'Customer preference not established'};
async function api(path:string,body?:unknown){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const x:any=await r.json();if(!r.ok)throw new Error(x.error??'Unable to complete this operation.');return x}
export default function Home(){
 const [result,setResult]=useState<CallResult|null>(null),[scenario,setScenario]=useState<Scenario>('barrier'),[reviewed,setReviewed]=useState(false),[action,setAction]=useState<Action>('seek_confirmation'),[mode,setMode]=useState<'sample'|'live'>('sample');
 const [venue,setVenue]=useState('The Courtyard — fictional restaurant'),[context,setContext]=useState('I would like to bring my family for Sunday lunch. Can you explain your step-free seating and toilet facilities?'),[plan,setPlan]=useState<any>(null),[approved,setApproved]=useState(false),[callId,setCallId]=useState(''),[state,setState]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[caps,setCaps]=useState<any>(null);
 const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{api('/api/capabilities').then(setCaps).catch(()=>setCaps({liveReady:false}));const saved=new URLSearchParams(location.search).get('call');if(saved){setMode('live');setCallId(saved);setState('Saved call — refresh to load');}},[]);
 useEffect(()=>{if(result)heading.current?.focus()},[result]);
 function reset(){setResult(null);setReviewed(false);setAction('seek_confirmation');setPlan(null);setApproved(false);setError('');setNotice('')}
 function showSample(){reset();setResult(sample(scenario));setNotice('Sample result ready. Review the route answers and transcript below.')}
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function refresh(){await run(async()=>{const x=await api('/api/calls/'+encodeURIComponent(callId));setState(x.state);if(x.result){setResult(x.result);setReviewed(false)}else setNotice(x.state==='uncertain_dispatch'?'Dispatch is uncertain. Operator reconciliation is required; do not retry.':'Call result is not ready. Refresh again in at least 15 seconds. This page does not monitor in the background.');})}
 const preview=result&&reviewed?JSON.stringify(exportReview(result,action,true),null,2):'';
 async function download(){if(!result||!reviewed)return;await run(async()=>{const out=mode==='live'?await api('/api/calls/'+encodeURIComponent(callId)+'/review',{action,reviewed:true}):exportReview(result,action,true);if(JSON.stringify(out)!==JSON.stringify(exportReview(result,action,true)))throw new Error('Saved review changed. Reload before exporting.');const url=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='before-we-go-reviewed.json';a.click();URL.revokeObjectURL(url);setNotice('Reviewed report downloaded.');})}
 useEffect(()=>{const d=document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}};if(!d.modelContext)return;const c=new AbortController();try{Promise.resolve(d.modelContext.registerTool({name:'read_visit_result',description:'Read the displayed Before We Go result, with explicit synthetic/live provenance. Does not call anyone or approve a review.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');return {mode,result,reviewed,nextAction:action}}},{signal:c.signal})).catch(()=>{})}catch{}return()=>c.abort()},[mode,result,reviewed,action]);
 return <main className="min-h-screen bg-background text-foreground"><header className="border-b bg-white px-6 py-5"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3"><a href="/" className="flex items-center gap-3 text-xl font-bold"><Footprints aria-hidden className="text-primary"/>Before We Go</a><span className="rounded-full bg-blue-50 px-4 py-2 text-sm font-medium text-blue-800">{mode==='sample'?'Fictional sample':'Private live test'}</span></div></header>
 <div className="mx-auto max-w-6xl px-6 py-10"><p className="mb-4 text-sm font-semibold uppercase tracking-widest text-primary">A thoughtful callback before the visit</p><h1 className="max-w-3xl text-4xl font-semibold leading-tight tracking-tight md:text-5xl">Ask once. Feel heard.<br/>Know what still needs checking.</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-muted-foreground">Our restaurant AI calls you back, explains the facts it has, and gives staff a clear handoff for anything it cannot answer.</p>
 <div className="mt-8 flex flex-wrap gap-3"><Button variant={mode==='sample'?'default':'outline'} disabled={busy} onClick={()=>{setMode('sample');reset()}}>Explore fictional examples</Button><Button variant={mode==='live'?'default':'outline'} disabled={busy} onClick={()=>{setMode('live');reset()}}>Private CALL-E test</Button></div>
 <p role="status" className="mt-4 text-sm text-blue-800">{notice}</p>{error&&<p role="alert" className="my-3 rounded-lg border border-red-200 bg-red-50 p-4 text-red-900">{error}</p>}
 <div className="mt-5 grid items-start gap-7 lg:grid-cols-[.85fr_1.15fr]"><section className="rounded-2xl border bg-white p-6 sm:p-7"><p className="text-sm font-semibold text-primary">01 / CUSTOMER ENQUIRY</p><h2 className="my-4 text-2xl font-semibold">Tell us about your visit</h2>
 {mode==='sample'?<><label className="mb-2 block font-medium">Example situation<Select value={scenario} onValueChange={v=>{if(v){setScenario(v as Scenario);reset()}}}><SelectTrigger className="mt-2 h-12 w-full"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(scenarios).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></label><p className="my-4 text-sm leading-relaxed text-muted-foreground">The Courtyard is fictional. You are the customer. CALL-E acts as the restaurant’s AI representative. All example dialogue is synthetic.</p></>:<><label htmlFor="venue" className="mb-2 block font-medium">Fictional venue</label><Input id="venue" maxLength={100} value={restaurant.name} readOnly/><label htmlFor="context" className="mb-2 mt-4 block font-medium">Your question for the restaurant</label><Input id="context" maxLength={500} value={context} onChange={e=>{setContext(e.target.value);reset()}}/><p className="mt-3 text-sm text-muted-foreground">Submit a question as the customer. This private test calls only your configured mobile number.</p></>}
 <ul className="my-6 space-y-4">{Object.values(requirements).map(x=><li key={x} className="flex gap-3"><Check aria-hidden className="h-5 w-5 shrink-0 text-primary"/>{x}</li>)}</ul><div className="rounded-xl bg-slate-50 p-4 text-sm leading-relaxed"><strong>Call objective</strong><p className="mt-1">Call back the customer, understand their preferences, explain only the supplied restaurant facts, and capture unresolved questions for staff. No booking is confirmed.</p></div>
 {mode==='sample'?<><Button onClick={showSample} className="mt-6 h-12 w-full">Explore sample result <ArrowRight aria-hidden/></Button><p className="mt-3 text-center text-sm text-muted-foreground">This button makes no call.</p></>:<div className="mt-6">{!caps?.liveReady?<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-relaxed"><strong>Live calling is not enabled</strong><p className="mt-2">An authorized operator, consented recipient and call budget must be configured first. API credentials stay on the server.</p>{!caps?.signedIn&&<a className="mt-3 inline-block underline" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a>}</div>:<Button disabled={busy||!!callId} className="h-12 w-full" onClick={()=>run(async()=>{reset();setPlan(await api('/api/preview',{venue,context}))})}>Preview customer callback</Button>}
 {plan&&<div className="mt-5 space-y-4 rounded-xl border p-4"><p className="font-semibold">{plan.recipient}</p><p className="text-sm">{plan.notice} Approval expires in 10 minutes.</p><details><summary className="cursor-pointer font-medium">Exact outgoing instructions</summary><p className="mt-3 whitespace-pre-wrap text-sm">{plan.task}</p></details><label className="flex gap-3 text-sm"><Checkbox checked={approved} onCheckedChange={v=>setApproved(v===true)}/>I reviewed the instructions and confirm this recipient agreed to this test and transcript capture.</label><Button disabled={!approved||busy||!!callId} onClick={()=>run(async()=>{const x=await api('/api/start',{planId:plan.id,approved:true});setCallId(x.id);setState(x.state);history.replaceState(null,'','?call='+encodeURIComponent(x.id));setPlan(null);setNotice('Call dispatch recorded. Keep this page to check the result.');})}>Start my test callback</Button></div>}
 {callId&&<div className="mt-4 rounded-xl border p-4"><p className="font-medium">{state.replaceAll('_',' ')}</p><Button className="mt-3" variant="outline" disabled={busy} onClick={refresh}>Refresh saved call</Button><p className="mt-2 text-sm text-muted-foreground">No automatic redial. Keep this URL to return to this call.</p></div>}</div>}</section>
 <section className="rounded-2xl border bg-white p-6 sm:p-7"><p className="text-sm font-semibold text-primary">02 / CONVERSATION → STAFF HANDOFF</p>{!result?<div className="py-10"><CircleHelp aria-hidden className="mb-5 h-9 w-9 text-primary"/><h2 className="text-2xl font-semibold">Good service includes knowing when to check.</h2><p className="mt-4 leading-relaxed text-muted-foreground">The assistant knows the entrance is step-free. It does not know whether a suitable table is available. It should explain that difference clearly, then capture what staff need to confirm.</p><blockquote className="mt-8 border-l-4 border-primary pl-5 text-lg">“I can explain our facilities, and flag what staff still need to confirm.”<p className="mt-2 text-sm text-muted-foreground">Fictional restaurant AI representative</p></blockquote></div>:<><h2 ref={heading} tabIndex={-1} className="mt-4 text-2xl font-semibold focus-visible:outline-2 focus-visible:outline-primary">Review the customer callback</h2><p className="mt-2 text-sm font-medium text-muted-foreground">{result.mode} · {result.venue}</p>{result.issues.map(x=><p key={x} className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-950">{x}</p>)}{result.openQuestions.length>0&&<div className="mt-4 rounded-xl bg-amber-50 p-4"><h3 className="font-semibold">Questions staff still need to answer</h3><ul className="mt-2 list-disc space-y-2 pl-5 text-sm">{result.openQuestions.map((q,i)=><li key={i}>{q}</li>)}</ul></div>}<div className="mt-6 space-y-4">{result.requirements.map(c=><article key={c.id} className="rounded-xl border p-4"><div className="flex gap-3">{c.effective==='unknown'?<TriangleAlert aria-hidden className="h-5 w-5 shrink-0 text-amber-700"/>:<CircleHelp aria-hidden className="h-5 w-5 shrink-0 text-primary"/>}<div><h3 className="font-semibold">{c.label}</h3><p className="text-sm">{labels[c.effective]}</p></div></div><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{c.detail}</p>{c.quote&&<blockquote className="mt-3 border-l-2 pl-3 text-sm">“{c.quote}”<p className="mt-2 text-xs text-muted-foreground">{c.evidence==='matched'?'Exact customer excerpt; review meaning in context.':'Excerpt could not be matched to customer speech; preference stays unresolved.'}</p>{c.turnIds.map(id=><a key={id} href={'#'+id} className="mr-3 mt-2 inline-block text-primary underline">View {id}</a>)}</blockquote>}{c.follow_up&&<p className="mt-3 text-sm"><strong>Follow-up:</strong> {c.follow_up}</p>}{c.agent_quote&&<blockquote className="mt-3 rounded-lg bg-blue-50 p-3 text-sm"><strong>AI explanation:</strong> “{c.agent_quote}”<p className="mt-2 text-xs">{c.agentTurnIds.length?'Matched to AI speech; check it against the fact sheet below.':'Not matched to AI speech; review required.'}</p></blockquote>}</article>)}</div>
 <details className="mt-6 rounded-xl border p-4" open><summary className="cursor-pointer font-semibold">Full transcript context ({result.turns.length} turns)</summary><p className="mt-2 text-sm text-muted-foreground">Exact matching does not prove meaning. Look for customer corrections, misleading promises and questions still awaiting a staff answer.</p><ol className="mt-4 space-y-3">{result.turns.map(t=><li key={t.id} id={t.id} tabIndex={-1} className="scroll-mt-6 rounded-lg bg-slate-50 p-3 text-sm target:ring-2 target:ring-blue-500"><strong>{t.speaker==='agent'?'Restaurant AI':'Customer'} · {t.id}</strong><p className="mt-1 leading-relaxed">{t.text}</p></li>)}</ol>{!result.turns.length&&<p className="mt-3 text-sm">No transcript available. Staff need to review the unanswered enquiry.</p>}</details>
 <label className="mt-6 block font-semibold">Staff next action<Select value={action} onValueChange={v=>{if(v){setAction(v as Action);setReviewed(false)}}}><SelectTrigger className="mt-2 h-auto min-h-12 w-full whitespace-normal"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(actions).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></label><label className="mt-5 flex cursor-pointer items-start gap-3 text-sm leading-relaxed"><Checkbox className="mt-1" checked={reviewed} onCheckedChange={v=>setReviewed(v===true)}/>I reviewed the customer’s needs, the AI’s explanation against the fact sheet, and the unresolved questions. This does not confirm a booking or guarantee access.</label>{reviewed&&<details className="mt-5" open><summary className="cursor-pointer font-semibold">Exact report to download</summary><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-slate-950 p-4 text-xs text-slate-100">{preview}</pre></details>}<Button disabled={!reviewed||busy} onClick={download} className="mt-5 h-12 w-full">Download reviewed report</Button></>}</section></div><section className="mt-7 rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Restaurant fact sheet · fictional demo</h2><p className="mt-2 text-sm text-muted-foreground">This is what the AI receives before the call. Version: {(result?.knowledge??restaurant).version}. It has no live booking database.</p><div className="mt-5 grid gap-5 md:grid-cols-3">{(result?.knowledge??restaurant).facts.map(f=><article key={f.id}><h3 className="font-semibold">{f.label}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{f.text}</p></article>)}</div><p className="mt-4 text-sm text-muted-foreground">{(result?.knowledge??restaurant).general}</p></section><footer className="mt-8 max-w-3xl text-sm leading-relaxed text-muted-foreground">The restaurant facts are fictional and versioned for this demo. A live callback tests the integration, not a real business’s facilities. Unanswered questions remain with staff; no booking or callback time is promised.</footer></div></main>
}
